// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuTc-2GZt9a7gkk-Sxm8iowKV4QPNHWY',
    appId: '1:74541411013:web:4061f296eb42e2d838deac',
    messagingSenderId: '74541411013',
    projectId: 'whitedov-d2bea',
    authDomain: 'whitedov-d2bea.firebaseapp.com',
    storageBucket: 'whitedov-d2bea.firebasestorage.app',
    measurementId: 'G-BYHL4Y2D3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfVHhpAgtUY411pE1O7fs_GeGl_0upJA',
    appId: '1:74541411013:android:f0cd4ef67db74bd238deac',
    messagingSenderId: '74541411013',
    projectId: 'whitedov-d2bea',
    storageBucket: 'whitedov-d2bea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeuWDYhZ69Sgs39b7H6cYdrlbsa8Tph0I',
    appId: '1:74541411013:ios:bc8ed0e71f22406e38deac',
    messagingSenderId: '74541411013',
    projectId: 'whitedov-d2bea',
    storageBucket: 'whitedov-d2bea.firebasestorage.app',
    iosBundleId: 'com.example.bahm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeuWDYhZ69Sgs39b7H6cYdrlbsa8Tph0I',
    appId: '1:74541411013:ios:bc8ed0e71f22406e38deac',
    messagingSenderId: '74541411013',
    projectId: 'whitedov-d2bea',
    storageBucket: 'whitedov-d2bea.firebasestorage.app',
    iosBundleId: 'com.example.bahm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZuTc-2GZt9a7gkk-Sxm8iowKV4QPNHWY',
    appId: '1:74541411013:web:3190c13ccc9179ac38deac',
    messagingSenderId: '74541411013',
    projectId: 'whitedov-d2bea',
    authDomain: 'whitedov-d2bea.firebaseapp.com',
    storageBucket: 'whitedov-d2bea.firebasestorage.app',
    measurementId: 'G-T7JF1VDYWR',
  );
}
